baseURL = "https://benstopford.com/"
languageCode = "en-us"
title = "Ben Stopford"
theme = "PaperMod"

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[params.label]
  text = "ben stopford"

[params]
  author = "Ben Stopford"
  description = "Writing on distributed systems, data, and software engineering"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/aboutme/"
    weight = 2
